### ISSUE TITLE
KneeXraydata

### ISSUE THREAD

**Issue by DAVID0325** [PingjunChen/KneeAnalysis#1]
Is there a duplicate of the images in kneeKL224 and kneeKL229 in the folder name ClskLData?
https://data.mendeley.com/datasets/56rmx5bjcr/1

**Comment by PingjunChen** [comment]
Sorry for this really late reply, as I didn't notice this issue until today. The images in  kneeKL224  and kneeKL299 are with the same content and only differ in size. I prepare two versions for different models. kneeKL299 for InceptionV3, and kneeKL224 for VGG, ResNet, etc.
